#############################################################################
# Makefile for building: QLuach
# Generated by qmake (2.01a) (Qt 4.5.2) on: Thu Sep 24 22:25:53 2009
# Project:  QLuach.pro
# Template: app
# Command: /home/moshe/qtsdk-2009.03/qt/bin/qmake -spec ../qtsdk-2009.03/qt/mkspecs/linux-g++ -unix -o Makefile QLuach.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qtsdk-2009.03/qt/mkspecs/linux-g++ -I. -I../qtsdk-2009.03/qt/include/QtCore -I../qtsdk-2009.03/qt/include/QtGui -I../qtsdk-2009.03/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/moshe/qtsdk-2009.03/qt/lib
LIBS          = $(SUBLIBS)  -L/home/moshe/qtsdk-2009.03/qt/lib -lhdate -lQtGui -L/home/moshe/qtsdk-2009.03/qt/lib -L/usr/X11R6/lib -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/moshe/qtsdk-2009.03/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		daybutton.cpp \
		functions.cpp \
		mhdate.cpp moc_mainwindow.cpp \
		moc_daybutton.cpp \
		moc_mhdate.cpp \
		qrc_QLuach.cpp
OBJECTS       = main.o \
		mainwindow.o \
		daybutton.o \
		functions.o \
		mhdate.o \
		moc_mainwindow.o \
		moc_daybutton.o \
		moc_mhdate.o \
		qrc_QLuach.o
DIST          = ../qtsdk-2009.03/qt/mkspecs/common/g++.conf \
		../qtsdk-2009.03/qt/mkspecs/common/unix.conf \
		../qtsdk-2009.03/qt/mkspecs/common/linux.conf \
		../qtsdk-2009.03/qt/mkspecs/qconfig.pri \
		../qtsdk-2009.03/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2009.03/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2009.03/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2009.03/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2009.03/qt/mkspecs/features/release.prf \
		../qtsdk-2009.03/qt/mkspecs/features/default_post.prf \
		../qtsdk-2009.03/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2009.03/qt/mkspecs/features/qt.prf \
		../qtsdk-2009.03/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2009.03/qt/mkspecs/features/moc.prf \
		../qtsdk-2009.03/qt/mkspecs/features/resources.prf \
		../qtsdk-2009.03/qt/mkspecs/features/uic.prf \
		../qtsdk-2009.03/qt/mkspecs/features/yacc.prf \
		../qtsdk-2009.03/qt/mkspecs/features/lex.prf \
		../qtsdk-2009.03/qt/mkspecs/features/include_source_dir.prf \
		QLuach.pro
QMAKE_TARGET  = QLuach
DESTDIR       = 
TARGET        = QLuach

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QLuach.pro  ../qtsdk-2009.03/qt/mkspecs/linux-g++/qmake.conf ../qtsdk-2009.03/qt/mkspecs/common/g++.conf \
		../qtsdk-2009.03/qt/mkspecs/common/unix.conf \
		../qtsdk-2009.03/qt/mkspecs/common/linux.conf \
		../qtsdk-2009.03/qt/mkspecs/qconfig.pri \
		../qtsdk-2009.03/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2009.03/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2009.03/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2009.03/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2009.03/qt/mkspecs/features/release.prf \
		../qtsdk-2009.03/qt/mkspecs/features/default_post.prf \
		../qtsdk-2009.03/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2009.03/qt/mkspecs/features/qt.prf \
		../qtsdk-2009.03/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2009.03/qt/mkspecs/features/moc.prf \
		../qtsdk-2009.03/qt/mkspecs/features/resources.prf \
		../qtsdk-2009.03/qt/mkspecs/features/uic.prf \
		../qtsdk-2009.03/qt/mkspecs/features/yacc.prf \
		../qtsdk-2009.03/qt/mkspecs/features/lex.prf \
		../qtsdk-2009.03/qt/mkspecs/features/include_source_dir.prf \
		/home/moshe/qtsdk-2009.03/qt/lib/libQtGui.prl \
		/home/moshe/qtsdk-2009.03/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../qtsdk-2009.03/qt/mkspecs/linux-g++ -unix -o Makefile QLuach.pro
../qtsdk-2009.03/qt/mkspecs/common/g++.conf:
../qtsdk-2009.03/qt/mkspecs/common/unix.conf:
../qtsdk-2009.03/qt/mkspecs/common/linux.conf:
../qtsdk-2009.03/qt/mkspecs/qconfig.pri:
../qtsdk-2009.03/qt/mkspecs/features/qt_functions.prf:
../qtsdk-2009.03/qt/mkspecs/features/qt_config.prf:
../qtsdk-2009.03/qt/mkspecs/features/exclusive_builds.prf:
../qtsdk-2009.03/qt/mkspecs/features/default_pre.prf:
../qtsdk-2009.03/qt/mkspecs/features/release.prf:
../qtsdk-2009.03/qt/mkspecs/features/default_post.prf:
../qtsdk-2009.03/qt/mkspecs/features/warn_on.prf:
../qtsdk-2009.03/qt/mkspecs/features/qt.prf:
../qtsdk-2009.03/qt/mkspecs/features/unix/thread.prf:
../qtsdk-2009.03/qt/mkspecs/features/moc.prf:
../qtsdk-2009.03/qt/mkspecs/features/resources.prf:
../qtsdk-2009.03/qt/mkspecs/features/uic.prf:
../qtsdk-2009.03/qt/mkspecs/features/yacc.prf:
../qtsdk-2009.03/qt/mkspecs/features/lex.prf:
../qtsdk-2009.03/qt/mkspecs/features/include_source_dir.prf:
/home/moshe/qtsdk-2009.03/qt/lib/libQtGui.prl:
/home/moshe/qtsdk-2009.03/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qtsdk-2009.03/qt/mkspecs/linux-g++ -unix -o Makefile QLuach.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QLuach1.0.0 || $(MKDIR) .tmp/QLuach1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QLuach1.0.0/ && $(COPY_FILE) --parents mainwindow.h daybutton.h functions.h mhdate.h .tmp/QLuach1.0.0/ && $(COPY_FILE) --parents QLuach.qrc .tmp/QLuach1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp daybutton.cpp functions.cpp mhdate.cpp .tmp/QLuach1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/QLuach1.0.0/ && (cd `dirname .tmp/QLuach1.0.0` && $(TAR) QLuach1.0.0.tar QLuach1.0.0 && $(COMPRESS) QLuach1.0.0.tar) && $(MOVE) `dirname .tmp/QLuach1.0.0`/QLuach1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QLuach1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_daybutton.cpp moc_mhdate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_daybutton.cpp moc_mhdate.cpp
moc_mainwindow.cpp: daybutton.h \
		functions.h \
		mhdate.h \
		mainwindow.h
	/home/moshe/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_daybutton.cpp: functions.h \
		daybutton.h
	/home/moshe/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) daybutton.h -o moc_daybutton.cpp

moc_mhdate.cpp: functions.h \
		mhdate.h
	/home/moshe/qtsdk-2009.03/qt/bin/moc $(DEFINES) $(INCPATH) mhdate.h -o moc_mhdate.cpp

compiler_rcc_make_all: qrc_QLuach.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QLuach.cpp
qrc_QLuach.cpp: QLuach.qrc \
		Icons/arrow-left-double.png \
		Icons/icon.png \
		Icons/arrow-right.png \
		Icons/arrow-left.png \
		Icons/arrow-right-double.png
	/home/moshe/qtsdk-2009.03/qt/bin/rcc -name QLuach QLuach.qrc -o qrc_QLuach.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/moshe/qtsdk-2009.03/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		daybutton.h \
		functions.h \
		mhdate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		daybutton.h \
		functions.h \
		mhdate.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

daybutton.o: daybutton.cpp daybutton.h \
		functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o daybutton.o daybutton.cpp

functions.o: functions.cpp functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o functions.cpp

mhdate.o: mhdate.cpp mhdate.h \
		functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mhdate.o mhdate.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_daybutton.o: moc_daybutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_daybutton.o moc_daybutton.cpp

moc_mhdate.o: moc_mhdate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mhdate.o moc_mhdate.cpp

qrc_QLuach.o: qrc_QLuach.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QLuach.o qrc_QLuach.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

