#############################################################################
# Makefile for building: Luach
# Generated by qmake (2.01a) (Qt 4.5.3) on: Mon Oct 12 21:50:22 2009
# Project:  Luach.pro
# Template: app
# Command: /home/moshe/qtsdk-2009.04/qt/bin/qmake -spec ../qtsdk-2009.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Luach.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qtsdk-2009.04/qt/mkspecs/linux-g++ -I. -I../qtsdk-2009.04/qt/include/QtCore -I../qtsdk-2009.04/qt/include/QtGui -I../qtsdk-2009.04/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/moshe/qtsdk-2009.04/qt/lib
LIBS          = $(SUBLIBS)  -L/home/moshe/qtsdk-2009.04/qt/lib -lhdate -lQtGui -L/home/moshe/qtsdk-2009.04/qt/lib -L/usr/X11R6/lib -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/moshe/qtsdk-2009.04/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		daybutton.cpp \
		functions.cpp \
		mhdate.cpp \
		changelocation.cpp \
		about.cpp moc_mainwindow.cpp \
		moc_daybutton.cpp \
		moc_mhdate.cpp \
		moc_changelocation.cpp \
		moc_about.cpp \
		qrc_Luach.cpp
OBJECTS       = main.o \
		mainwindow.o \
		daybutton.o \
		functions.o \
		mhdate.o \
		changelocation.o \
		about.o \
		moc_mainwindow.o \
		moc_daybutton.o \
		moc_mhdate.o \
		moc_changelocation.o \
		moc_about.o \
		qrc_Luach.o
DIST          = ../qtsdk-2009.04/qt/mkspecs/common/g++.conf \
		../qtsdk-2009.04/qt/mkspecs/common/unix.conf \
		../qtsdk-2009.04/qt/mkspecs/common/linux.conf \
		../qtsdk-2009.04/qt/mkspecs/qconfig.pri \
		../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2009.04/qt/mkspecs/features/debug.prf \
		../qtsdk-2009.04/qt/mkspecs/features/default_post.prf \
		../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2009.04/qt/mkspecs/features/qt.prf \
		../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2009.04/qt/mkspecs/features/moc.prf \
		../qtsdk-2009.04/qt/mkspecs/features/resources.prf \
		../qtsdk-2009.04/qt/mkspecs/features/uic.prf \
		../qtsdk-2009.04/qt/mkspecs/features/yacc.prf \
		../qtsdk-2009.04/qt/mkspecs/features/lex.prf \
		../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf \
		Luach.pro
QMAKE_TARGET  = Luach
DESTDIR       = 
TARGET        = Luach

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_changelocation.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Luach.pro  ../qtsdk-2009.04/qt/mkspecs/linux-g++/qmake.conf ../qtsdk-2009.04/qt/mkspecs/common/g++.conf \
		../qtsdk-2009.04/qt/mkspecs/common/unix.conf \
		../qtsdk-2009.04/qt/mkspecs/common/linux.conf \
		../qtsdk-2009.04/qt/mkspecs/qconfig.pri \
		../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2009.04/qt/mkspecs/features/debug.prf \
		../qtsdk-2009.04/qt/mkspecs/features/default_post.prf \
		../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2009.04/qt/mkspecs/features/qt.prf \
		../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2009.04/qt/mkspecs/features/moc.prf \
		../qtsdk-2009.04/qt/mkspecs/features/resources.prf \
		../qtsdk-2009.04/qt/mkspecs/features/uic.prf \
		../qtsdk-2009.04/qt/mkspecs/features/yacc.prf \
		../qtsdk-2009.04/qt/mkspecs/features/lex.prf \
		../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf \
		/home/moshe/qtsdk-2009.04/qt/lib/libQtGui.prl \
		/home/moshe/qtsdk-2009.04/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../qtsdk-2009.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Luach.pro
../qtsdk-2009.04/qt/mkspecs/common/g++.conf:
../qtsdk-2009.04/qt/mkspecs/common/unix.conf:
../qtsdk-2009.04/qt/mkspecs/common/linux.conf:
../qtsdk-2009.04/qt/mkspecs/qconfig.pri:
../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf:
../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf:
../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf:
../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf:
../qtsdk-2009.04/qt/mkspecs/features/debug.prf:
../qtsdk-2009.04/qt/mkspecs/features/default_post.prf:
../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf:
../qtsdk-2009.04/qt/mkspecs/features/qt.prf:
../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf:
../qtsdk-2009.04/qt/mkspecs/features/moc.prf:
../qtsdk-2009.04/qt/mkspecs/features/resources.prf:
../qtsdk-2009.04/qt/mkspecs/features/uic.prf:
../qtsdk-2009.04/qt/mkspecs/features/yacc.prf:
../qtsdk-2009.04/qt/mkspecs/features/lex.prf:
../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf:
/home/moshe/qtsdk-2009.04/qt/lib/libQtGui.prl:
/home/moshe/qtsdk-2009.04/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qtsdk-2009.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Luach.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Luach1.0.0 || $(MKDIR) .tmp/Luach1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Luach1.0.0/ && $(COPY_FILE) --parents mainwindow.h daybutton.h functions.h mhdate.h changelocation.h about.h .tmp/Luach1.0.0/ && $(COPY_FILE) --parents Luach.qrc .tmp/Luach1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp daybutton.cpp functions.cpp mhdate.cpp changelocation.cpp about.cpp .tmp/Luach1.0.0/ && $(COPY_FILE) --parents mainwindow.ui changelocation.ui about.ui .tmp/Luach1.0.0/ && (cd `dirname .tmp/Luach1.0.0` && $(TAR) Luach1.0.0.tar Luach1.0.0 && $(COMPRESS) Luach1.0.0.tar) && $(MOVE) `dirname .tmp/Luach1.0.0`/Luach1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Luach1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_daybutton.cpp moc_mhdate.cpp moc_changelocation.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_daybutton.cpp moc_mhdate.cpp moc_changelocation.cpp moc_about.cpp
moc_mainwindow.cpp: mhdate.h \
		functions.h \
		daybutton.h \
		changelocation.h \
		about.h \
		mainwindow.h
	/home/moshe/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_daybutton.cpp: functions.h \
		daybutton.h
	/home/moshe/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) daybutton.h -o moc_daybutton.cpp

moc_mhdate.cpp: functions.h \
		mhdate.h
	/home/moshe/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) mhdate.h -o moc_mhdate.cpp

moc_changelocation.cpp: functions.h \
		changelocation.h
	/home/moshe/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) changelocation.h -o moc_changelocation.cpp

moc_about.cpp: about.h
	/home/moshe/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_Luach.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Luach.cpp
qrc_Luach.cpp: Luach.qrc \
		Icons/help-about.png \
		Icons/arrow-left-double.png \
		Icons/exit.png \
		Icons/icon.png \
		Icons/arrow-right.png \
		Icons/document-print.png \
		Icons/arrow-left.png \
		Icons/calendar.png \
		Icons/arrow-right-double.png \
		Icons/location.png
	/home/moshe/qtsdk-2009.04/qt/bin/rcc -name Luach Luach.qrc -o qrc_Luach.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_changelocation.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_changelocation.h ui_about.h
ui_mainwindow.h: mainwindow.ui
	/home/moshe/qtsdk-2009.04/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_changelocation.h: changelocation.ui
	/home/moshe/qtsdk-2009.04/qt/bin/uic changelocation.ui -o ui_changelocation.h

ui_about.h: about.ui
	/home/moshe/qtsdk-2009.04/qt/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mhdate.h \
		functions.h \
		daybutton.h \
		changelocation.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mhdate.h \
		functions.h \
		daybutton.h \
		changelocation.h \
		about.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

daybutton.o: daybutton.cpp daybutton.h \
		functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o daybutton.o daybutton.cpp

functions.o: functions.cpp functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o functions.cpp

mhdate.o: mhdate.cpp mhdate.h \
		functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mhdate.o mhdate.cpp

changelocation.o: changelocation.cpp changelocation.h \
		functions.h \
		ui_changelocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changelocation.o changelocation.cpp

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_daybutton.o: moc_daybutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_daybutton.o moc_daybutton.cpp

moc_mhdate.o: moc_mhdate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mhdate.o moc_mhdate.cpp

moc_changelocation.o: moc_changelocation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changelocation.o moc_changelocation.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_Luach.o: qrc_Luach.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Luach.o qrc_Luach.cpp

####### Install

install_binary: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	-$(INSTALL_PROGRAM) /home/moshe/Luach/Luach $(INSTALL_ROOT)/usr/local/bin/


uninstall_binary:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/bin/Luach
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install_zmanim: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	-$(INSTALL_FILE) /home/moshe/Luach/ZmanimCLI.jar $(INSTALL_ROOT)/usr/local/bin/


uninstall_zmanim:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/bin/ZmanimCLI.jar
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install:  install_binary install_zmanim  FORCE

uninstall: uninstall_binary uninstall_zmanim   FORCE

FORCE:

